image: vitorbertulucci/docker-compose:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  PRIVATE_TOKEN: "PRIVATE-TOKEN: $CI_JOB_TOKEN"
  CONTAINER_TEST_IMAGE: "registry.gitlab.com/legallabs/challenger-frontend/challenger-frontend:$CI_COMMIT_REF_NAME"
  CONTAINER_RELEASE_IMAGE: "registry.gitlab.com/legallabs/challenger-frontend/challenger-frontend:latest"
  CONTAINER_STAGING_IMAGE: "registry.gitlab.com/legallabs/challenger-frontend/challenger-frontend:staging"

before_script:
  - apk update && apk add curl
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker-compose --version

stages:
  - build

build:
  stage: build
  script:
    - 'docker pull $CONTAINER_TEST_IMAGE || docker pull $CONTAINER_STAGING_IMAGE || true'
    - docker build --cache-from $CONTAINER_RELEASE_IMAGE --cache-from $CONTAINER_TEST_IMAGE -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
